#!/usr/bin/env bash
# Run AFTER: npx firebase-tools login
# Creates Firebase project, Firestore, web app, deploys rules, writes firebase-config.js

set -euo pipefail
cd "$(dirname "$0")/.."

FB="npx firebase-tools"
PROJECT_ID="${1:-sugar-coat-bakers-stall}"

echo "→ Checking Firebase login…"
if ! $FB login:list 2>&1 | grep -q "Logged in"; then
  echo "Not logged in. Run first:"
  echo "  npx firebase-tools login"
  exit 1
fi

echo "→ Creating project: $PROJECT_ID"
if ! $FB projects:create "$PROJECT_ID" --display-name "Sugar Coat Bakers" 2>/dev/null; then
  echo "  (Project may already exist — continuing)"
fi

$FB use "$PROJECT_ID"

echo "→ Creating Firestore (asia-south1)…"
if ! $FB firestore:databases:create --location asia-south1 2>/dev/null; then
  echo "  (Database may already exist — continuing)"
fi

echo "→ Deploying security rules…"
$FB deploy --only firestore:rules --project "$PROJECT_ID"

echo "→ Creating web app…"
APP_ID=$($FB apps:create WEB "Sugar Coat Stall" --project "$PROJECT_ID" --json 2>/dev/null | grep -o '"appId": "[^"]*"' | head -1 | cut -d'"' -f4 || true)

if [ -z "$APP_ID" ]; then
  echo "→ Web app may exist, fetching config…"
  APP_ID=$($FB apps:list WEB --project "$PROJECT_ID" --json | grep -o '"appId": "[^"]*"' | head -1 | cut -d'"' -f4)
fi

echo "→ Writing firebase-config.js…"
$FB apps:sdkconfig WEB "$APP_ID" --project "$PROJECT_ID" > /tmp/firebase-sdk.txt

node << 'NODE'
const fs = require('fs');
const raw = fs.readFileSync('/tmp/firebase-sdk.txt', 'utf8');
const match = raw.match(/const firebaseConfig = (\{[\s\S]*?\});/);
if (!match) {
  console.error('Could not parse Firebase SDK config. Output was:\n', raw);
  process.exit(1);
}
const config = match[1];
const out = `/* Auto-generated by scripts/setup-firebase.sh */\nconst FIREBASE_CONFIG = ${config};\n`;
fs.writeFileSync('firebase-config.js', out);
console.log('Wrote firebase-config.js');
NODE

echo ""
echo "✅ Almost done! ONE manual step in Firebase Console:"
echo "   Authentication → Sign-in method → Anonymous → Enable → Save"
echo "   https://console.firebase.google.com/project/$PROJECT_ID/authentication/providers"
echo ""
echo "Then deploy:"
echo "   git add firebase-config.js && git commit -m 'Add Firebase config' && git push"
